# Generated by Django 2.1.5 on 2019-01-29 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woner', to=settings.AUTH_USER_MODEL),
        ),
    ]
